#Default deny all traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: golang-app
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
#Allow port 5432 on Pods of app: postgres from itself pods only from/to the namespace golang-app
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-itself-port5432
  namespace: golang-app
spec:
  podSelector:
    matchLabels:
      app: postgres
  ingress:
  - ports:
    - port: 5432
    from:
    - podSelector:
        matchLabels:
          app: postgres
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: golang-app 
    - ipBlock:
        cidr: 127.0.0.1/32
  egress:
  - ports:
    - port: 5432
    to:
    - podSelector:
        matchLabels:
          app: postgres
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: golang-app
    - ipBlock:
        cidr: 127.0.0.1/32
---
#Allow port 5432 on Pods of app: postgres from pods on app: pgpool only from/to the namespace golang-app
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-pgpool-port5432
  namespace: golang-app
spec:
  podSelector:
    matchLabels:
      app: postgres
  ingress:
  - ports:
    - port: 5432
    from:
    - podSelector:
        matchLabels:
          app: pgpool
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: golang-app 
  egress:
  - ports:
    - port: 5432
    to:
    - podSelector:
        matchLabels:
          app: pgpool
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: golang-app 
---
#Allow port 5432 on Pods of app: pgpool from pods on id: app-golang only from/to the namespace golang-app
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-app-golang-port5432
  namespace: golang-app
spec:
  podSelector:
    matchLabels:
      app: pgpool
  ingress:
  - ports:
    - port: 5432
    from:
    - podSelector:
        matchLabels:
          id: app-golang
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: golang-app 
  egress:
  - ports:
    - port: 5432
    to:
    - podSelector:
        matchLabels:
          id: app-golang
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: golang-app 
---
#Allow port 8080 of app id: app-golang from anywhere
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-app-golang-port8080
  namespace: golang-app
spec:
  podSelector:
    matchLabels:
      id: app-golang
  ingress:
  - ports:
    - port: 8080
  egress:
  - ports:
    - port: 8080
